name: Deploy Ai-based-mockinterview-system-backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            source ~/.nvm/nvm.sh;
            source ~/.bashrc;
            cd ~/zala-projects/ai-powered-mock-interview-system-backend &&
            git pull origin main &&
            npm install &&
            npm run build &&
            pm2 restart ai-based-mockinterview-system-backend || pm2 start dist/index.js --name ai-based-mockinterview-system-backend &&
            pm2 save
          "
